### PR TITLE
Added session level bruteforce protection on latest code

### PR DESCRIPTION
**Pull request by Oscar-Rydh**

### CODE REVIEW

**Comment by VictorWinberg** [comment]
This could be a duplicate of a work-in-progress solution on the database.

**Comment by VictorWinberg** [comment]
If PR #48 will come through, this PR could be closed.

**Comment by HannaLindwall** [comment]
Yes, I think this is one could be closed (?)

**Review by HannaLindwall — COMMENTED** [review]
This should not be merged

**Pull request closed without merging**
