### PR TITLE
Fixing post without login v2

### LINKED ISSUE #27: POST requests bypasses login?
Somehow it seems like we can perform CSRF-attacks, without being logged on. It feels like POST-requests bypasses our check if user is logged on **or** the user is still logged on?

### PR DESCRIPTION
**Pull request by VictorWinberg**
Closes #27 with bracket fix.

### CODE REVIEW

**Review by HannaLindwall — COMMENTED** [review]
So now we cool?

**Comment by VictorWinberg** [comment]
Yeah, I think so. Maybe we should fix the formatting tho.

**Comment by Oscar-Rydh** [comment]
Danke!

**Comment by Oscar-Rydh** [comment]
Lägger till CSRF skydd på denna PR

**Review by VictorWinberg — COMMENTED** [review]
Without testing it, the code looks good to me ;)

**Comment by HannaLindwall** [comment]
Same

**Comment by VictorWinberg** [comment]
Csrf protection closes #27

**Comment by VictorWinberg** [comment]
Csrf protection closes #26

**Review by tovesson — APPROVED** [review]
Looks good!

**Pull request merged**
